#initial guess for fitting parameters
#if you don't have initial guess for any coefficinet, it will be found such as: 
# E0 1 w_min w_max
#gamma  1 1e-2 100
# A  1 1e-2 500

N #number of oscillators
8

E0 coefficients: #E0_init, low_bound, up_bound
3   2.0 3.8
4.8 4.6 5.0
6.8 6.5 7.0
15  10  20
23  20  25
26  20  30
38  35  45

gamma coefficients: #gamma_init, low_bound, up_bound

A coefficients: #A_init, low_bound, up_bound
-0.5 -1 -.1e-5
